# -*- coding: utf-8 -*-
"""bleu_dos_4_modelos_ (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EY_yQRzQzyJnNSWR31LBahsJYB9hzb4J

## A ##
"""

# ---------------------------
# CÉLULA 1: INSTALAÇÃO DE DEPENDÊNCIAS
# Execute esta célula primeiro no notebook
# ---------------------------
!pip install --upgrade pip
!pip install transformers sentencepiece sacremoses accelerate datasets
# Instala torch (CPU por padrão). Se quiser versão CUDA, troque conforme instruções do site do PyTorch.
!pip install torch

# ---------------------------
# CÉLULA 2: CÓDIGO COMPLETO (TRADUÇÃO COM 4 MODELOS + CHUNKING)
# ---------------------------

import re
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, MBartForConditionalGeneration, MBart50TokenizerFast
import pandas as pd
from typing import List

# Detecta dispositivo
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Usando dispositivo: {device}")

# Modelos
MODELOS = {
    "NLLB":       "facebook/nllb-200-distilled-600M",
    "M2M100-418M":"facebook/m2m100_418M",
    "FLAN-T5":    "google/flan-t5-large",
    "MBART":      "facebook/mbart-large-50-many-to-many-mmt"
}

# Cache para evitar recarregar os modelos a cada chamada
_model_cache = {}

def load_tokenizer_model(model_key):
    if model_key in _model_cache:
        return _model_cache[model_key]
    model_name = MODELOS[model_key]
    if model_key == "MBART":
        tokenizer = MBart50TokenizerFast.from_pretrained(model_name)
        model = MBartForConditionalGeneration.from_pretrained(model_name)
    else:
        tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
        model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    model.to(device)
    _model_cache[model_key] = (tokenizer, model)
    return tokenizer, model

# Função de split em sentenças simples
def split_into_sentences(text: str) -> List[str]:
    text = text.strip()
    sents = re.split(r'(?<=[\.\.\?\!])\s+(?=[^\s])', text)
    sents = [s.strip() for s in sents if s.strip()]
    return sents if sents else [text]

# Chunking por tokens estimados via tokenizer
def chunk_sentences_by_token_limit(sentences: List[str], tokenizer, max_tokens: int = 400) -> List[str]:
    chunks = []
    cur = []
    cur_toks = 0
    for s in sentences:
        toks = len(tokenizer.tokenize(s))
        if toks > max_tokens:
            if cur:
                chunks.append(" ".join(cur)); cur = []; cur_toks = 0
            words = s.split()
            piece = []; piece_toks = 0
            for w in words:
                wtoks = len(tokenizer.tokenize(w))
                if piece_toks + wtoks > max_tokens:
                    if piece: chunks.append(" ".join(piece))
                    piece = [w]; piece_toks = wtoks
                else:
                    piece.append(w); piece_toks += wtoks
            if piece: chunks.append(" ".join(piece))
            continue
        if cur_toks + toks <= max_tokens:
            cur.append(s); cur_toks += toks
        else:
            if cur: chunks.append(" ".join(cur))
            cur = [s]; cur_toks = toks
    if cur: chunks.append(" ".join(cur))
    return chunks

# ── NLLB: generate() direto ──────────────────────────────────────────────────
def translate_nllb(text: str, src_lang: str, tgt_lang: str, max_tokens: int = 350) -> str:
    tokenizer, model = load_tokenizer_model("NLLB")
    tokenizer.src_lang = src_lang
    sents  = split_into_sentences(text)
    chunks = chunk_sentences_by_token_limit(sents, tokenizer, max_tokens)
    results = []
    for chunk in chunks:
        inputs = tokenizer(chunk, return_tensors="pt", truncation=True, padding=True).to(device)
        tgt_id = tokenizer.convert_tokens_to_ids(tgt_lang)
        out    = model.generate(**inputs, forced_bos_token_id=tgt_id,
                                max_length=1024, num_beams=4, early_stopping=True)
        results.append(tokenizer.decode(out[0], skip_special_tokens=True))
    return " ".join(results)

# ── M2M100: generate() direto ────────────────────────────────────────────────
def translate_m2m(text: str, src_lang: str, tgt_lang: str, max_tokens: int = 350) -> str:
    tokenizer, model = load_tokenizer_model("M2M100-418M")
    tokenizer.src_lang = src_lang
    sents  = split_into_sentences(text)
    chunks = chunk_sentences_by_token_limit(sents, tokenizer, max_tokens)
    results = []
    for chunk in chunks:
        inputs = tokenizer(chunk, return_tensors="pt", truncation=True, padding=True).to(device)
        tgt_id = tokenizer.get_lang_id(tgt_lang)
        out    = model.generate(**inputs, forced_bos_token_id=tgt_id,
                                max_length=1024, num_beams=4, early_stopping=True)
        results.append(tokenizer.decode(out[0], skip_special_tokens=True))
    return " ".join(results)

# ── FLAN-T5: generate() com prompt ───────────────────────────────────────────
def translate_flan(text: str, max_tokens: int = 250) -> str:
    tokenizer, model = load_tokenizer_model("FLAN-T5")
    sents  = split_into_sentences(text)
    chunks = chunk_sentences_by_token_limit(sents, tokenizer, max_tokens)
    results = []
    for chunk in chunks:
        prompt = f"Translate the following text from Portuguese to Italian:\n\n{chunk}\n\nTranslate:"
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, padding=True).to(device)
        out    = model.generate(**inputs, max_length=1024, num_beams=4, early_stopping=True)
        results.append(tokenizer.decode(out[0], skip_special_tokens=True))
    return " ".join(results)

# ── MBART: generate() direto ─────────────────────────────────────────────────
def translate_mbart(text: str, src_lang: str, tgt_lang: str, max_tokens: int = 350) -> str:
    tokenizer, model = load_tokenizer_model("MBART")
    tokenizer.src_lang = src_lang
    sents  = split_into_sentences(text)
    chunks = chunk_sentences_by_token_limit(sents, tokenizer, max_tokens)
    tgt_id = tokenizer.lang_code_to_id[tgt_lang]
    results = []
    for chunk in chunks:
        inputs = tokenizer(chunk, return_tensors="pt", truncation=True, padding=True).to(device)
        out    = model.generate(**inputs, forced_bos_token_id=tgt_id,
                                max_length=1024, num_beams=4, early_stopping=True)
        results.append(tokenizer.decode(out[0], skip_special_tokens=True))
    return " ".join(results)

# ── Função central ────────────────────────────────────────────────────────────
def translate_text_all_models(text: str, src="pt", tgt="it"):
    nllb_codes  = {"pt": "por_Latn", "it": "ita_Latn"}
    m2m_codes   = {"pt": "pt",       "it": "it"}   # M2M100 usa ISO 639-1
    mbart_codes = {"pt": "pt_XX",    "it": "it_IT"}

    return {
        "NLLB":       translate_nllb( text, nllb_codes[src],  nllb_codes[tgt]),
        "M2M100_418M":translate_m2m(  text, m2m_codes[src],   m2m_codes[tgt]),
        "FLAN_T5":    translate_flan(  text),
        "MBART":      translate_mbart(text, mbart_codes[src], mbart_codes[tgt]),
    }

# ── Métricas simples ──────────────────────────────────────────────────────────
def jaccard_similarity(a: str, b: str) -> float:
    sa = set(a.lower().split()); sb = set(b.lower().split())
    if not sa and not sb: return 1.0
    if not sa or  not sb: return 0.0
    return len(sa & sb) / len(sa | sb)

def overlap_ratio(a: str, b: str) -> float:
    ta = a.lower().split(); tb = set(b.lower().split())
    if not ta: return 0.0
    return sum(1 for t in ta if t in tb) / len(ta)

# ── Processador de pares REF x AUTO ──────────────────────────────────────────
def process_pairs(ref_texts, auto_texts, src="pt", tgt="it"):
    rows = []
    n = min(len(ref_texts), len(auto_texts))
    for i in range(n):
        ref = ref_texts[i]; auto = auto_texts[i]
        tr_ref  = translate_text_all_models(ref,  src=src, tgt=tgt)
        tr_auto = translate_text_all_models(auto, src=src, tgt=tgt)
        for model_name in tr_ref:
            rows.append({
                "Paragrafo_Index": i + 1,
                "Modelo":          model_name,
                "REF_pt":          ref,
                "AUTO_pt":         auto,
                "REF_tr":          tr_ref[model_name],
                "AUTO_tr":         tr_auto[model_name],
                "Jaccard":         jaccard_similarity(tr_ref[model_name], tr_auto[model_name]),
                "Overlap_ratio":   overlap_ratio(tr_ref[model_name], tr_auto[model_name]),
            })
    return pd.DataFrame(rows)

# ---------------------------
# EXEMPLO (substitua REF e AUTO pelas suas listas)
# ---------------------------
if __name__ == "__main__":
    REF = [
        "Exemplo longo de referência. Este parágrafo pode ter mais de mil palavras — o código fará chunking automaticamente.",
        "Segundo parágrafo de referência para teste."
    ]
    AUTO = [
        "Exemplo longo gerado automaticamente. Também pode exceder limites e será dividido.",
        "Segundo parágrafo automático."
    ]
    df = process_pairs(REF, AUTO, src="pt", tgt="it")
    print(df.head())
    df.to_csv("comparativo_traducao_4_modelos.csv", index=False)
    print("Salvo: comparativo_traducao_4_modelos.csv")

def plot_metricas_medias(df, metrica):
    import matplotlib.pyplot as plt
    import seaborn as sns

    medias = df.groupby("Modelo")[metrica].mean().sort_values()

    plt.figure(figsize=(10, 5))
    sns.barplot(x=medias.values, y=medias.index, palette="Set2")

    plt.title(f"Média de {metrica} por Modelo", fontsize=18)
    plt.xlabel(metrica)
    plt.ylabel("Modelo")

    plt.grid(axis='x', linestyle='--', alpha=0.4)
    plt.tight_layout()
    plt.show()

plot_metricas_medias(df, "Jaccard")

"""---
## Avaliação Multimétrica (METEOR · chrF · TER)

> Além de Jaccard/Overlap, aplicamos agora **METEOR**, **chrF** e **TER** (do notebook de métricas principal).
> Lembre: TER quanto **menor**, melhor.
"""

# Avaliação METEOR, chrF e TER sobre os pares REF x AUTO
# Requer que o DataFrame 'df' já esteja carregado (gerado pela célula process_pairs acima)

!pip install sacrebleu
import pandas as pd
import matplotlib.pyplot as plt
import sacrebleu
import nltk
from nltk.translate.meteor_score import single_meteor_score

nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('omw-1.4', quiet=True)

def calcular_metricas(traducao, referencia):
    """Calcula METEOR, chrF e TER para um par (tradução, referência)."""
    try:
        meteor = single_meteor_score(
            nltk.word_tokenize(str(referencia), language='portuguese'),
            nltk.word_tokenize(str(traducao), language='portuguese')
        ) * 100
    except Exception:
        meteor = 0.0
    chrf = sacrebleu.sentence_chrf(str(traducao), [str(referencia)]).score
    ter  = sacrebleu.sentence_ter(str(traducao), [str(referencia)]).score
    return {'METEOR': round(meteor, 2), 'chrF': round(chrf, 2), 'TER': round(ter, 2)}

# Aplica as métricas comparando REF_tr vs AUTO_tr (traduções em inglês)
resultados = []
for _, row in df.iterrows():
    m = calcular_metricas(str(row['AUTO_tr']), str(row['REF_tr']))
    resultados.append({'Modelo': row['Modelo'], 'Paragrafo': row['Paragrafo_Index'], **m})

df_metricas = pd.DataFrame(resultados)

# Médias por modelo
medias = df_metricas.groupby('Modelo')[['METEOR', 'chrF', 'TER']].mean().round(2)
print('=== MÉDIAS METEOR / chrF / TER POR MODELO ===')
print(medias.to_string())
print('\nNota: TER — quanto MENOR, melhor.')

# Gráfico comparativo
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle('METEOR · chrF · TER por Modelo (Comparativo)', fontsize=14, fontweight='bold')
metricas_plot = [('METEOR', 'METEOR (maior=melhor)'), ('chrF', 'chrF (maior=melhor)'), ('TER', 'TER (menor=melhor)')]
cores = ['#2196F3', '#FF9800', '#4CAF50', '#9C27B0']
for ax, (met, titulo) in zip(axes, metricas_plot):
    vals = medias[met].values
    modelos = medias.index.tolist()
    bars = ax.bar(modelos, vals, color=cores[:len(modelos)], edgecolor='white', alpha=0.85)
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5, f'{v:.1f}',
                ha='center', va='bottom', fontsize=9, fontweight='bold')
    ax.set_title(titulo, fontsize=11)
    ax.set_ylabel('Score')
    ax.grid(axis='y', linestyle='--', alpha=0.5)
    ax.set_ylim(0, max(vals) * 1.2 + 5 if len(vals) > 0 else 100)
plt.tight_layout()
plt.savefig('metricas_bleu4modelos_meteor_chrf_ter.png', dpi=150, bbox_inches='tight')
plt.show()
print('Gráfico salvo em metricas_bleu4modelos_meteor_chrf_ter.png')

"""---
## Análise Estatística — Desvio padrão · Diferença de médias · Teste pareado

> Esta seção adiciona, sobre os scores **por segmento** já calculados acima:
> - **Desvio padrão** (amostral, `ddof=1`), erro padrão e IC 95% por modelo;
> - **Teste de diferença de médias (omnibus):** ANOVA de um fator e, quando há ≥3 modelos, o teste de **Friedman** (pareado, não-paramétrico);
> - **Testes pareados par a par:** **t pareado** (`ttest_rel`) e **Wilcoxon** (signed-rank), com tamanho de efeito (Cohen *dz*) e correção de **Bonferroni**;
> - **Gráficos:** barras de média ± desvio padrão (com os pontos por segmento) e **mapa de calor** dos p-valores dos testes pareados.
>
> A avaliação é **pareada**: cada segmento (verso/parágrafo) é pontuado por todos os modelos, então as colunas ficam alinhadas pelo mesmo segmento.

"""

import warnings; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd
from scipy import stats
import itertools

# ---------------------------------------------------------------
# DESVIO PADRÃO + TESTE DE DIFERENÇA DE MÉDIAS + TESTE PAREADO
# (função reutilizável; avaliação pareada = mesmo segmento por modelo)
# ---------------------------------------------------------------
def analise_estatistica_modelos(scores_por_modelo, nome_metrica="Métrica",
                                maior_melhor=True, alpha=0.05, imprimir=True,
                                plotar=True, salvar_em=None):
    modelos = list(scores_por_modelo.keys())
    dados = {m: np.asarray(scores_por_modelo[m], dtype=float) for m in modelos}

    # ---- validação de tamanho (necessário para teste pareado) ----
    tamanhos = {m: len(v) for m, v in dados.items()}
    n = min(tamanhos.values())
    if len(set(tamanhos.values())) > 1:
        if imprimir:
            print(f"[aviso] modelos com nº de segmentos diferente {tamanhos}; "
                  f"truncando para n={n} para permitir teste pareado.")
        dados = {m: v[:n] for m, v in dados.items()}

    # =================================================================
    # 1) ESTATÍSTICAS DESCRITIVAS  (inclui o DESVIO PADRÃO pedido)
    # =================================================================
    linhas = []
    for m in modelos:
        x = dados[m]
        media = x.mean()
        desv = x.std(ddof=1)                       # desvio padrão amostral
        ep = desv / np.sqrt(len(x))                # erro padrão da média
        tcrit = stats.t.ppf(1 - alpha / 2, len(x) - 1)
        ic_low, ic_high = media - tcrit * ep, media + tcrit * ep
        linhas.append({
            "Modelo": m, "n": len(x),
            "Média": round(media, 3),
            "Desvio_Padrão": round(desv, 3),
            "Erro_Padrão": round(ep, 3),
            "IC95%_inf": round(ic_low, 3),
            "IC95%_sup": round(ic_high, 3),
        })
    desc = pd.DataFrame(linhas)
    melhor = (desc.loc[desc["Média"].idxmax()] if maior_melhor
              else desc.loc[desc["Média"].idxmin()])

    # =================================================================
    # 2) TESTE DE DIFERENÇA DE MÉDIAS (OMNIBUS)
    # =================================================================
    grupos = [dados[m] for m in modelos]
    omnibus = {}
    if len(modelos) >= 2:
        # ANOVA de um fator (paramétrica)
        f_stat, p_anova = stats.f_oneway(*grupos)
        omnibus["ANOVA_F"] = round(float(f_stat), 4)
        omnibus["ANOVA_p"] = float(p_anova)
        # Friedman (não-paramétrico, pareado) — exige >=3 grupos
        if len(modelos) >= 3:
            try:
                chi, p_fried = stats.friedmanchisquare(*grupos)
                omnibus["Friedman_chi2"] = round(float(chi), 4)
                omnibus["Friedman_p"] = float(p_fried)
            except Exception as e:
                omnibus["Friedman_erro"] = str(e)

    # =================================================================
    # 3) TESTES PAREADOS PAR A PAR
    # =================================================================
    pares = list(itertools.combinations(modelos, 2))
    n_comp = len(pares)
    linhas_par = []
    for a, b in pares:
        xa, xb = dados[a], dados[b]
        dif = xa - xb
        sd_dif = dif.std(ddof=1)
        if np.allclose(dif, 0):
            # diferença nula em todos os segmentos -> sem diferença
            t_stat, p_t, w_stat, p_w, dz = 0.0, 1.0, np.nan, 1.0, 0.0
        elif sd_dif == 0:
            # diferença CONSTANTE (variância zero) -> determinística
            t_stat, p_t = np.inf * np.sign(dif.mean()), 0.0
            try:
                w_stat, p_w = stats.wilcoxon(xa, xb)
            except Exception:
                w_stat, p_w = np.nan, 0.0
            dz = np.inf * np.sign(dif.mean())
        else:
            try:
                t_stat, p_t = stats.ttest_rel(xa, xb)
            except Exception:
                t_stat, p_t = np.nan, np.nan
            try:
                w_stat, p_w = stats.wilcoxon(xa, xb)
            except Exception:
                w_stat, p_w = np.nan, np.nan
            dz = dif.mean() / sd_dif
        p_bonf = min(p_t * n_comp, 1.0) if not np.isnan(p_t) else np.nan
        linhas_par.append({
            "Par": f"{a} vs {b}",
            "Dif_média": round(float(dif.mean()), 3),
            "t": (round(float(t_stat), 3) if np.isfinite(t_stat) else t_stat),
            "p_t_pareado": p_t,
            "p_Wilcoxon": p_w,
            "p_t_Bonferroni": p_bonf,
            "Cohen_dz": (round(float(dz), 3) if np.isfinite(dz) else dz),
            "Signif_(α=%.2f)" % alpha: "sim" if (not np.isnan(p_bonf) and p_bonf < alpha) else "não",
        })
    pareado = pd.DataFrame(linhas_par)

    # ---- impressão amigável ----
    if imprimir:
        print(f"\n{'='*70}\nANÁLISE ESTATÍSTICA — {nome_metrica} "
              f"({'maior=melhor' if maior_melhor else 'menor=melhor'}) | n={n} segmentos\n{'='*70}")
        print("\n• Descritivas (média ± desvio padrão):")
        print(desc.to_string(index=False))
        print(f"\n  → melhor média: {melhor['Modelo']} "
              f"({melhor['Média']} ± {melhor['Desvio_Padrão']})")
        if omnibus:
            print("\n• Teste de diferença de médias (omnibus):")
            if "ANOVA_p" in omnibus:
                sig = "DIFERENÇA significativa" if omnibus["ANOVA_p"] < alpha else "sem diferença significativa"
                print(f"    ANOVA 1 fator: F={omnibus['ANOVA_F']}, "
                      f"p={omnibus['ANOVA_p']:.4g}  → {sig}")
            if "Friedman_p" in omnibus:
                sig = "DIFERENÇA significativa" if omnibus["Friedman_p"] < alpha else "sem diferença significativa"
                print(f"    Friedman (pareado): χ²={omnibus['Friedman_chi2']}, "
                      f"p={omnibus['Friedman_p']:.4g}  → {sig}")
        print("\n• Testes PAREADOS par a par (t pareado + Wilcoxon):")
        pp = pareado.copy()
        for col in ["p_t_pareado", "p_Wilcoxon", "p_t_Bonferroni"]:
            pp[col] = pp[col].map(lambda v: f"{v:.4g}" if pd.notna(v) else "—")
        print(pp.to_string(index=False))
        print("\n  Nota: p_t_Bonferroni corrige o nº de comparações; "
              "Cohen_dz é o tamanho de efeito pareado.")

    # =================================================================
    # 4) GRÁFICOS  (desvio padrão + diferença de médias + teste pareado)
    # =================================================================
    if plotar:
        import matplotlib.pyplot as plt
        n_mod = len(modelos)
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13.5, 5.2),
                                       gridspec_kw={"width_ratios": [1.15, 1]})
        cores = plt.cm.Set2(np.linspace(0, 1, max(n_mod, 3)))[:n_mod]

        # --- AX1: barras média ± desvio padrão + pontos por segmento ---
        medias = np.array([dados[m].mean() for m in modelos])
        desvs = np.array([dados[m].std(ddof=1) for m in modelos])
        xpos = np.arange(n_mod)
        bars = ax1.bar(xpos, medias, yerr=desvs, capsize=6, color=cores,
                       edgecolor="white", alpha=0.85, error_kw={"elinewidth": 1.5})
        for i, m in enumerate(modelos):
            y = dados[m]
            jit = (np.random.RandomState(0).rand(len(y)) - 0.5) * 0.35
            ax1.scatter(np.full(len(y), i) + jit, y, s=16, color="#333",
                        alpha=0.45, zorder=3)
        # destaca o melhor
        idx_best = (int(medias.argmax()) if maior_melhor else int(medias.argmin()))
        bars[idx_best].set_edgecolor("#d62728")
        bars[idx_best].set_linewidth(2.5)
        for i, (mu, sd) in enumerate(zip(medias, desvs)):
            ax1.text(i, mu + sd + (medias.max() * 0.02 + 0.5),
                     f"{mu:.1f}±{sd:.1f}", ha="center", va="bottom",
                     fontsize=9, fontweight="bold")
        ax1.set_xticks(xpos)
        ax1.set_xticklabels(modelos, rotation=20, ha="right", fontsize=9)
        ax1.set_ylabel(nome_metrica)
        sentido = "maior=melhor" if maior_melhor else "menor=melhor"
        ax1.set_title(f"Média ± desvio padrão · pontos por segmento\n({sentido}; borda vermelha = melhor)",
                      fontsize=10)
        ax1.grid(axis="y", linestyle="--", alpha=0.4)

        # --- AX2: mapa de calor dos p-valores pareados (t pareado, Bonferroni) ---
        P = np.full((n_mod, n_mod), np.nan)
        idx = {m: i for i, m in enumerate(modelos)}
        for _, r in pareado.iterrows():
            a, b = r["Par"].split(" vs ")
            pv = r["p_t_Bonferroni"]
            P[idx[a], idx[b]] = pv
            P[idx[b], idx[a]] = pv
        with np.errstate(divide="ignore"):
            M = -np.log10(np.clip(P, 1e-300, 1.0))   # maior = mais significativo
        im = ax2.imshow(M, cmap="YlOrRd", vmin=0,
                        vmax=max(3.0, np.nanmax(M) if np.isfinite(np.nanmax(M)) else 3.0))
        ax2.set_xticks(range(n_mod)); ax2.set_yticks(range(n_mod))
        ax2.set_xticklabels(modelos, rotation=30, ha="right", fontsize=8)
        ax2.set_yticklabels(modelos, fontsize=8)

        def estrelas(p):
            if np.isnan(p): return ""
            if p < 0.001: return "***"
            if p < 0.01:  return "**"
            if p < 0.05:  return "*"
            return "ns"
        for i in range(n_mod):
            for j in range(n_mod):
                if i == j:
                    ax2.text(j, i, "—", ha="center", va="center", color="#999")
                elif not np.isnan(P[i, j]):
                    p = P[i, j]
                    txt = ("<0.001" if p < 0.001 else f"{p:.3f}") + f"\n{estrelas(p)}"
                    cor = "white" if M[i, j] > 2 else "black"
                    ax2.text(j, i, txt, ha="center", va="center", fontsize=7.5, color=cor)
        ax2.set_title("Teste pareado — p (t pareado, Bonferroni)\n*** p<0.001  ** p<0.01  * p<0.05  ns=não signif.",
                      fontsize=9.5)
        cb = fig.colorbar(im, ax=ax2, fraction=0.046, pad=0.04)
        cb.set_label("-log10(p)", fontsize=8)

        fig.suptitle(f"Análise estatística — {nome_metrica}", fontsize=13, fontweight="bold")
        fig.tight_layout(rect=[0, 0, 1, 0.95])
        if salvar_em:
            fig.savefig(salvar_em, dpi=150, bbox_inches="tight")
            if imprimir:
                print(f"  Gráfico salvo em {salvar_em}")
        plt.show()

    return {"descritivas": desc, "omnibus": omnibus, "pareado": pareado}

# >>> Requer 'df_metricas' (gerado pela célula METEOR/chrF/TER acima),
#     com colunas: Modelo, Paragrafo, METEOR, chrF, TER.
for _metrica, _maior in [('METEOR', True), ('chrF', True), ('TER', False)]:
    _piv = df_metricas.pivot_table(index='Paragrafo', columns='Modelo',
                                   values=_metrica, aggfunc='mean').dropna()
    scores_por_modelo = {m: _piv[m].values for m in _piv.columns}
    analise_estatistica_modelos(scores_por_modelo, _metrica, maior_melhor=_maior)