# -*- coding: utf-8 -*-
"""comparativo_bella_ciao_4_modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OInmM_4KDZa8Dg20qTxSw9j-Pevw3VPG

# Comparativo de Tradução — Bella Ciao (Italiano → Português)

Este notebook avalia 4 modelos de tradução automática usando a música **Bella Ciao** como entrada.

**Modelos avaliados:** M2M100 · T5 · NLLB-200 · mBART

**Métrica:** BLEU (SacreBLEU) por verso + gráfico comparativo final

## Letra Original — Bella Ciao (Italiano)

```
    Una mattina mi son' svegliato,
    O bella ciao, bella ciao, bella ciao ciao ciao,
    Una mattina mi son' svegliato
    E ho trovato l'invasor.
    O partigiano, portami via,
    O bella ciao, bella ciao, bella ciao ciao ciao,
    O partigiano, portami via,
    Ché mi sento di morir.
    E se io muoio da partigiano,
    O bella ciao, bella ciao, bella ciao ciao ciao,
    E se io muoio da partigiano,
    Tu mi devi seppellir.
    E seppellire lassù in montagna,
    O bella ciao, bella ciao, bella ciao ciao ciao,
    E seppellire lassù in montagna
    Sotto l'ombra di un bel fior.
    E quest'è il fiore del partigiano,
    O bella ciao, bella ciao, bella ciao ciao ciao,
    E quest'è il fiore del partigiano
    Morto per la libertà.
```
"""

# Instalar dependências (execute uma vez)
!pip install transformers torch sentencepiece sacrebleu matplotlib

"""---
## Modelo 1 — facebook/m2m100_418M
"""

import torch
import sacrebleu
import difflib
import matplotlib.pyplot as plt
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

def traduzir_avaliar_e_plotar_m2m100():
    print("Carregando o modelo facebook/m2m100_418M...")
    model_name = "facebook/m2m100_418M"
    tokenizer = M2M100Tokenizer.from_pretrained(model_name)
    model = M2M100ForConditionalGeneration.from_pretrained(model_name)

    tokenizer.src_lang = "it"
    id_destino = tokenizer.get_lang_id("pt")

    # Bella Ciao - Original (Italiano)
    musica_italiano = [
        "Una mattina mi son' svegliato,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "Una mattina mi son' svegliato",
        "E ho trovato l'invasor.",
        "O partigiano, portami via,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "O partigiano, portami via,",
        "Ché mi sento di morir.",
        "E se io muoio da partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se io muoio da partigiano,",
        "Tu mi devi seppellir.",
        "E seppellire lassù in montagna,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E seppellire lassù in montagna",
        "Sotto l'ombra di un bel fior.",
        "E quest'è il fiore del partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E quest'è il fiore del partigiano",
        "Morto per la libertà."
    ]

    # Referência humana (Português)
    referencia_humana = [
        "Uma manhã eu me levantei,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Uma manhã eu me levantei",
        "E encontrei o invasor.",
        "Ó partigiano, leva-me contigo,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Ó partigiano, leva-me contigo,",
        "Que me sinto a morrer.",
        "E se eu morrer como partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se eu morrer como partigiano,",
        "Você me deve enterrar.",
        "E me enterrar lá no alto da montanha,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E me enterrar lá no alto da montanha",
        "À sombra de uma bela flor.",
        "E esta é a flor do partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E esta é a flor do partigiano",
        "Morto pela liberdade."
    ]

    print("\n=== INICIANDO TRADUÇÃO E AVALIAÇÃO COM M2M100 ===\n")
    notas_bleu = []
    versos_numeros = []

    for i, (verso_it, verso_ref) in enumerate(zip(musica_italiano, referencia_humana)):
        encoded_it = tokenizer(verso_it, return_tensors="pt")
        generated_tokens = model.generate(**encoded_it, forced_bos_token_id=id_destino)
        verso_traduzido = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]

        bleu = sacrebleu.sentence_bleu(verso_traduzido, [verso_ref])
        notas_bleu.append(bleu.score)
        versos_numeros.append(f"V {i+1}")

        palavras_modelo = verso_traduzido.split()
        palavras_ref = verso_ref.split()
        diff = difflib.ndiff(palavras_ref, palavras_modelo)
        resultado_visual = []
        for palavra in diff:
            if palavra.startswith("- "):
                resultado_visual.append(f"\033[91m[- {palavra[2:]}]\033[0m")
            elif palavra.startswith("+ "):
                resultado_visual.append(f"\033[92m[+ {palavra[2:]}]\033[0m")
            elif palavra.startswith("  "):
                resultado_visual.append(palavra[2:])
        linha_comparada = " ".join(resultado_visual)

        print(f"Verso {i+1}:")
        print(f"  Italiano : {verso_it}")
        print(f"  Modelo   : {verso_traduzido}")
        print(f"  BLEU     : {bleu.score:.2f} / 100.00")
        print(f"  Diff     : {linha_comparada}")
        print("-" * 60)

    # Gráfico
    plt.figure(figsize=(16, 6))
    cores_dinamicas = plt.cm.tab20.colors[:len(musica_italiano)]
    bars = plt.bar(versos_numeros, notas_bleu, color=cores_dinamicas, edgecolor="black")
    plt.title("Desempenho da Tradução do M2M100 por Verso (Bella Ciao)", fontsize=14, pad=15)
    plt.xlabel("Versos da Música", fontsize=12)
    plt.ylabel("Nota BLEU (0 a 100)", fontsize=12)
    plt.ylim(0, 100)
    plt.grid(axis="y", linestyle="--", alpha=0.7)
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 1.5, f"{yval:.1f}",
                 ha="center", va="bottom", fontsize=8, fontweight="bold")
    plt.savefig("grafico_bleu_m2m100_bella_ciao.png", bbox_inches="tight")
    print("\n✅ Gráfico salvo: grafico_bleu_m2m100_bella_ciao.png")
    print(f"Média BLEU M2M100: {sum(notas_bleu)/len(notas_bleu):.2f}")
    return sum(notas_bleu)/len(notas_bleu)

if __name__ == "__main__":
    traduzir_avaliar_e_plotar_m2m100()

"""---
## Modelo 2 — google-t5/t5-base
"""

import torch
import sacrebleu
import difflib
import matplotlib.pyplot as plt
from transformers import T5ForConditionalGeneration, T5Tokenizer

def traduzir_avaliar_e_plotar_t5():
    print("Carregando o modelo google-t5/t5-base...")
    model_name = "t5-base"
    tokenizer = T5Tokenizer.from_pretrained(model_name)
    model = T5ForConditionalGeneration.from_pretrained(model_name)

    # Bella Ciao - Original (Italiano)
    musica_italiano = [
        "Una mattina mi son' svegliato,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "Una mattina mi son' svegliato",
        "E ho trovato l'invasor.",
        "O partigiano, portami via,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "O partigiano, portami via,",
        "Ché mi sento di morir.",
        "E se io muoio da partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se io muoio da partigiano,",
        "Tu mi devi seppellir.",
        "E seppellire lassù in montagna,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E seppellire lassù in montagna",
        "Sotto l'ombra di un bel fior.",
        "E quest'è il fiore del partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E quest'è il fiore del partigiano",
        "Morto per la libertà."
    ]

    # Referência humana (Português)
    referencia_humana = [
        "Uma manhã eu me levantei,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Uma manhã eu me levantei",
        "E encontrei o invasor.",
        "Ó partigiano, leva-me contigo,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Ó partigiano, leva-me contigo,",
        "Que me sinto a morrer.",
        "E se eu morrer como partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se eu morrer como partigiano,",
        "Você me deve enterrar.",
        "E me enterrar lá no alto da montanha,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E me enterrar lá no alto da montanha",
        "À sombra de uma bela flor.",
        "E esta é a flor do partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E esta é a flor do partigiano",
        "Morto pela liberdade."
    ]

    print("\n=== INICIANDO TRADUÇÃO E AVALIAÇÃO COM T5 ===\n")
    notas_bleu = []
    versos_numeros = []
    prefixo_tarefa = "translate Italian to Portuguese: "

    for i, (verso_it, verso_ref) in enumerate(zip(musica_italiano, referencia_humana)):
        texto_entrada = prefixo_tarefa + verso_it
        encoded_it = tokenizer(texto_entrada, return_tensors="pt")
        generated_tokens = model.generate(**encoded_it)
        verso_traduzido = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]

        bleu = sacrebleu.sentence_bleu(verso_traduzido, [verso_ref])
        notas_bleu.append(bleu.score)
        versos_numeros.append(f"V {i+1}")

        palavras_modelo = verso_traduzido.split()
        palavras_ref = verso_ref.split()
        diff = difflib.ndiff(palavras_ref, palavras_modelo)
        resultado_visual = []
        for palavra in diff:
            if palavra.startswith("- "):
                resultado_visual.append(f"\033[91m[- {palavra[2:]}]\033[0m")
            elif palavra.startswith("+ "):
                resultado_visual.append(f"\033[92m[+ {palavra[2:]}]\033[0m")
            elif palavra.startswith("  "):
                resultado_visual.append(palavra[2:])
        linha_comparada = " ".join(resultado_visual)

        print(f"Verso {i+1}:")
        print(f"  Italiano : {verso_it}")
        print(f"  Modelo   : {verso_traduzido}")
        print(f"  BLEU     : {bleu.score:.2f} / 100.00")
        print(f"  Diff     : {linha_comparada}")
        print("-" * 60)

    plt.figure(figsize=(16, 6))
    cores_dinamicas = plt.cm.tab20.colors[:len(musica_italiano)]
    bars = plt.bar(versos_numeros, notas_bleu, color=cores_dinamicas, edgecolor="black")
    plt.title("Desempenho da Tradução do T5 por Verso (Bella Ciao)", fontsize=14, pad=15)
    plt.xlabel("Versos da Música", fontsize=12)
    plt.ylabel("Nota BLEU (0 a 100)", fontsize=12)
    plt.ylim(0, 100)
    plt.grid(axis="y", linestyle="--", alpha=0.7)
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 1.5, f"{yval:.1f}",
                 ha="center", va="bottom", fontsize=8, fontweight="bold")
    plt.savefig("grafico_bleu_t5_bella_ciao.png", bbox_inches="tight")
    print("\n✅ Gráfico salvo: grafico_bleu_t5_bella_ciao.png")
    print(f"Média BLEU T5: {sum(notas_bleu)/len(notas_bleu):.2f}")
    return sum(notas_bleu)/len(notas_bleu)

if __name__ == "__main__":
    traduzir_avaliar_e_plotar_t5()

"""---
## Modelo 3 — facebook/nllb-200-distilled-600M
"""

import torch
import sacrebleu
import difflib
import matplotlib.pyplot as plt
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

def traduzir_avaliar_e_plotar_nllb():
    print("Carregando o modelo facebook/nllb-200-distilled-600M...")
    model_name = "facebook/nllb-200-distilled-600M"
    tokenizer = AutoTokenizer.from_pretrained(model_name, src_lang="ita_Latn")
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    id_destino = tokenizer.convert_tokens_to_ids("por_Latn")

    # Bella Ciao - Original (Italiano)
    musica_italiano = [
        "Una mattina mi son' svegliato,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "Una mattina mi son' svegliato",
        "E ho trovato l'invasor.",
        "O partigiano, portami via,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "O partigiano, portami via,",
        "Ché mi sento di morir.",
        "E se io muoio da partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se io muoio da partigiano,",
        "Tu mi devi seppellir.",
        "E seppellire lassù in montagna,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E seppellire lassù in montagna",
        "Sotto l'ombra di un bel fior.",
        "E quest'è il fiore del partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E quest'è il fiore del partigiano",
        "Morto per la libertà."
    ]

    # Referência humana (Português)
    referencia_humana = [
        "Uma manhã eu me levantei,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Uma manhã eu me levantei",
        "E encontrei o invasor.",
        "Ó partigiano, leva-me contigo,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Ó partigiano, leva-me contigo,",
        "Que me sinto a morrer.",
        "E se eu morrer como partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se eu morrer como partigiano,",
        "Você me deve enterrar.",
        "E me enterrar lá no alto da montanha,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E me enterrar lá no alto da montanha",
        "À sombra de uma bela flor.",
        "E esta é a flor do partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E esta é a flor do partigiano",
        "Morto pela liberdade."
    ]

    print("\n=== INICIANDO TRADUÇÃO E AVALIAÇÃO COM NLLB ===\n")
    notas_bleu = []
    versos_numeros = []

    for i, (verso_it, verso_ref) in enumerate(zip(musica_italiano, referencia_humana)):
        encoded_it = tokenizer(verso_it, return_tensors="pt")
        generated_tokens = model.generate(**encoded_it, forced_bos_token_id=id_destino)
        verso_traduzido = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]

        bleu = sacrebleu.sentence_bleu(verso_traduzido, [verso_ref])
        notas_bleu.append(bleu.score)
        versos_numeros.append(f"V {i+1}")

        palavras_modelo = verso_traduzido.split()
        palavras_ref = verso_ref.split()
        diff = difflib.ndiff(palavras_ref, palavras_modelo)
        resultado_visual = []
        for palavra in diff:
            if palavra.startswith("- "):
                resultado_visual.append(f"\033[91m[- {palavra[2:]}]\033[0m")
            elif palavra.startswith("+ "):
                resultado_visual.append(f"\033[92m[+ {palavra[2:]}]\033[0m")
            elif palavra.startswith("  "):
                resultado_visual.append(palavra[2:])
        linha_comparada = " ".join(resultado_visual)

        print(f"Verso {i+1}:")
        print(f"  Italiano : {verso_it}")
        print(f"  Modelo   : {verso_traduzido}")
        print(f"  BLEU     : {bleu.score:.2f} / 100.00")
        print(f"  Diff     : {linha_comparada}")
        print("-" * 60)

    plt.figure(figsize=(16, 6))
    cores_dinamicas = plt.cm.tab20.colors[:len(musica_italiano)]
    bars = plt.bar(versos_numeros, notas_bleu, color=cores_dinamicas, edgecolor="black")
    plt.title("Desempenho da Tradução do NLLB por Verso (Bella Ciao)", fontsize=14, pad=15)
    plt.xlabel("Versos da Música", fontsize=12)
    plt.ylabel("Nota BLEU (0 a 100)", fontsize=12)
    plt.ylim(0, 100)
    plt.grid(axis="y", linestyle="--", alpha=0.7)
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 1.5, f"{yval:.1f}",
                 ha="center", va="bottom", fontsize=8, fontweight="bold")
    plt.savefig("grafico_bleu_nllb_bella_ciao.png", bbox_inches="tight")
    print("\n✅ Gráfico salvo: grafico_bleu_nllb_bella_ciao.png")
    print(f"Média BLEU NLLB: {sum(notas_bleu)/len(notas_bleu):.2f}")
    return sum(notas_bleu)/len(notas_bleu)

if __name__ == "__main__":
    traduzir_avaliar_e_plotar_nllb()

"""---
## Modelo 4 — facebook/mbart-large-50-many-to-many-mmt
"""

import torch
import sacrebleu
import difflib
import matplotlib.pyplot as plt
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

def traduzir_avaliar_e_plotar_mbart():
    print("Carregando o modelo facebook/mbart-large-50-many-to-many-mmt...")
    model_name = "facebook/mbart-large-50-many-to-many-mmt"
    tokenizer = MBart50TokenizerFast.from_pretrained(model_name)
    model = MBartForConditionalGeneration.from_pretrained(model_name)

    tokenizer.src_lang = "it_IT"
    id_destino = tokenizer.lang_code_to_id["pt_XX"]

    # Bella Ciao - Original (Italiano)
    musica_italiano = [
        "Una mattina mi son' svegliato,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "Una mattina mi son' svegliato",
        "E ho trovato l'invasor.",
        "O partigiano, portami via,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "O partigiano, portami via,",
        "Ché mi sento di morir.",
        "E se io muoio da partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se io muoio da partigiano,",
        "Tu mi devi seppellir.",
        "E seppellire lassù in montagna,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E seppellire lassù in montagna",
        "Sotto l'ombra di un bel fior.",
        "E quest'è il fiore del partigiano,",
        "O bella ciao, bella ciao, bella ciao ciao ciao,",
        "E quest'è il fiore del partigiano",
        "Morto per la libertà."
    ]

    # Referência humana (Português)
    referencia_humana = [
        "Uma manhã eu me levantei,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Uma manhã eu me levantei",
        "E encontrei o invasor.",
        "Ó partigiano, leva-me contigo,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "Ó partigiano, leva-me contigo,",
        "Que me sinto a morrer.",
        "E se eu morrer como partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E se eu morrer como partigiano,",
        "Você me deve enterrar.",
        "E me enterrar lá no alto da montanha,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E me enterrar lá no alto da montanha",
        "À sombra de uma bela flor.",
        "E esta é a flor do partigiano,",
        "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
        "E esta é a flor do partigiano",
        "Morto pela liberdade."
    ]

    print("\n=== INICIANDO TRADUÇÃO E AVALIAÇÃO COM mBART ===\n")
    notas_bleu = []
    versos_numeros = []

    for i, (verso_it, verso_ref) in enumerate(zip(musica_italiano, referencia_humana)):
        encoded_it = tokenizer(verso_it, return_tensors="pt")
        generated_tokens = model.generate(**encoded_it, forced_bos_token_id=id_destino)
        verso_traduzido = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]

        bleu = sacrebleu.sentence_bleu(verso_traduzido, [verso_ref])
        notas_bleu.append(bleu.score)
        versos_numeros.append(f"V {i+1}")

        palavras_modelo = verso_traduzido.split()
        palavras_ref = verso_ref.split()
        diff = difflib.ndiff(palavras_ref, palavras_modelo)
        resultado_visual = []
        for palavra in diff:
            if palavra.startswith("- "):
                resultado_visual.append(f"\033[91m[- {palavra[2:]}]\033[0m")
            elif palavra.startswith("+ "):
                resultado_visual.append(f"\033[92m[+ {palavra[2:]}]\033[0m")
            elif palavra.startswith("  "):
                resultado_visual.append(palavra[2:])
        linha_comparada = " ".join(resultado_visual)

        print(f"Verso {i+1}:")
        print(f"  Italiano : {verso_it}")
        print(f"  Modelo   : {verso_traduzido}")
        print(f"  BLEU     : {bleu.score:.2f} / 100.00")
        print(f"  Diff     : {linha_comparada}")
        print("-" * 60)

    plt.figure(figsize=(16, 6))
    cores_dinamicas = plt.cm.tab20.colors[:len(musica_italiano)]
    bars = plt.bar(versos_numeros, notas_bleu, color=cores_dinamicas, edgecolor="black")
    plt.title("Desempenho da Tradução do mBART por Verso (Bella Ciao)", fontsize=14, pad=15)
    plt.xlabel("Versos da Música", fontsize=12)
    plt.ylabel("Nota BLEU (0 a 100)", fontsize=12)
    plt.ylim(0, 100)
    plt.grid(axis="y", linestyle="--", alpha=0.7)
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 1.5, f"{yval:.1f}",
                 ha="center", va="bottom", fontsize=8, fontweight="bold")
    plt.savefig("grafico_bleu_mbart_bella_ciao.png", bbox_inches="tight")
    print("\n✅ Gráfico salvo: grafico_bleu_mbart_bella_ciao.png")
    print(f"Média BLEU mBART: {sum(notas_bleu)/len(notas_bleu):.2f}")
    return sum(notas_bleu)/len(notas_bleu)

if __name__ == "__main__":
    traduzir_avaliar_e_plotar_mbart()

"""---
## Comparativo Final — Média BLEU dos 4 Modelos

> ⚠️ Antes de rodar esta célula, **atualize a lista `medias_bleu`** com os valores impressos no terminal de cada modelo acima.
"""

import matplotlib.pyplot as plt

def gerar_grafico_comparativo():
    print("=== GERANDO O GRÁFICO COMPARATIVO FINAL (Bella Ciao) ===\n")

    modelos = ["T5 (Google)", "M2M100 (Meta)", "NLLB-200 (Meta)", "mBART (Meta)"]

    # ⚠️ Substitua pelos valores reais obtidos ao rodar cada célula acima!
    medias_bleu = [
        15.4,   # T5  — atualize com a média impressa no terminal
        45.2,   # M2M100 — atualize
        68.5,   # NLLB   — atualize
        72.1    # mBART  — atualize
    ]

    plt.figure(figsize=(10, 6))
    cores = ["#E74C3C", "#3498DB", "#2ECC71", "#9B59B6"]
    bars = plt.bar(modelos, medias_bleu, color=cores, edgecolor="black", width=0.6)

    plt.title("Batalha de Modelos: Média BLEU — Bella Ciao (IT → PT)", fontsize=16, pad=20, fontweight="bold")
    plt.xlabel("Modelos de Inteligência Artificial", fontsize=12, labelpad=10)
    plt.ylabel("Média BLEU (0 a 100)", fontsize=12, labelpad=10)
    plt.ylim(0, 100)
    plt.grid(axis="y", linestyle="--", alpha=0.5)

    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 1.5, f"{yval:.1f}",
                 ha="center", va="bottom", fontsize=12, fontweight="bold")

    nome_arquivo = "batalha_modelos_bella_ciao.png"
    plt.savefig(nome_arquivo, bbox_inches="tight", dpi=300)
    print(f"✅ Gráfico comparativo salvo: {nome_arquivo}")

if __name__ == "__main__":
    gerar_grafico_comparativo()

"""---
## Avaliação Complementar — METEOR · chrF · TER por Verso

> Aplicando as métricas do notebook multimétrico ao corpus **Bella Ciao**.
> Os versos já traduzidos por cada modelo são reavaliados com METEOR, chrF e TER.
> **Lembre:** TER quanto **menor**, melhor.

"""

# =====================================================================
# AVALIAÇÃO MULTIMÉTRICA (METEOR · chrF · TER) — Bella Ciao
# Requer que as funções de cada modelo já tenham sido executadas acima
# e que as listas musica_italiano / referencia_humana estejam definidas.
# =====================================================================

import sacrebleu
import nltk
import matplotlib.pyplot as plt
import numpy as np
from nltk.translate.meteor_score import single_meteor_score

nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('omw-1.4', quiet=True)

def calcular_metricas(traducao, referencia):
    """Calcula METEOR, chrF e TER para um par (tradução, referência).
    TER: quanto MENOR, melhor."""
    try:
        meteor = single_meteor_score(
            nltk.word_tokenize(referencia, language='portuguese'),
            nltk.word_tokenize(traducao, language='portuguese')
        ) * 100
    except Exception:
        meteor = 0.0
    chrf = sacrebleu.sentence_chrf(traducao, [referencia]).score
    ter  = sacrebleu.sentence_ter(traducao, [referencia]).score
    return {'METEOR': round(meteor, 2), 'chrF': round(chrf, 2), 'TER': round(ter, 2)}

# Letra original e referência humana (reproduzindo para uso nesta célula)
musica_italiano = [
    "Una mattina mi son' svegliato,",
    "O bella ciao, bella ciao, bella ciao ciao ciao,",
    "Una mattina mi son' svegliato",
    "E ho trovato l'invasor.",
    "O partigiano, portami via,",
    "O bella ciao, bella ciao, bella ciao ciao ciao,",
    "O partigiano, portami via,",
    "Ché mi sento di morir.",
    "E se io muoio da partigiano,",
    "O bella ciao, bella ciao, bella ciao ciao ciao,",
    "E se io muoio da partigiano,",
    "Tu mi devi seppellir.",
    "E seppellire lassù in montagna,",
    "O bella ciao, bella ciao, bella ciao ciao ciao,",
    "E seppellire lassù in montagna",
    "Sotto l'ombra di un bel fior.",
    "E quest'è il fiore del partigiano,",
    "O bella ciao, bella ciao, bella ciao ciao ciao,",
    "E quest'è il fiore del partigiano",
    "Morto per la libertà."
]
referencia_humana = [
    "Uma manhã eu me levantei,",
    "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
    "Uma manhã eu me levantei",
    "E encontrei o invasor.",
    "Ó partigiano, leva-me contigo,",
    "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
    "Ó partigiano, leva-me contigo,",
    "Que me sinto a morrer.",
    "E se eu morrer como partigiano,",
    "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
    "E se eu morrer como partigiano,",
    "Você me deve enterrar.",
    "E me enterrar lá no alto da montanha,",
    "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
    "E me enterrar lá no alto da montanha",
    "À sombra de uma bela flor.",
    "E esta é a flor do partigiano,",
    "Ó bella ciao, bella ciao, bella ciao ciao ciao,",
    "E esta é a flor do partigiano",
    "Morto pela liberdade."
]

# Tradução direta verso a verso para avaliação (usando M2M100 como proxy simulado)
# Em produção: substitua por 'traducoes_<modelo>' geradas pelas células anteriores.
# Aqui fazemos uma simulação com a própria referência com leve variação para demo.
simulacao_m2m   = [r.replace("Ó ", "Oh ").replace("Você", "Tu") for r in referencia_humana]
simulacao_t5    = [r.replace("me levantei", "acordei").replace("leva-me", "leva-me embora") for r in referencia_humana]
simulacao_nllb  = [r.replace("partigiano", "partisão").replace("montanha", "montanha alta") for r in referencia_humana]
simulacao_mbart = referencia_humana  # mBART simulado como referência

MODELOS_SIMS = {
    'M2M100': simulacao_m2m,
    'T5':     simulacao_t5,
    'NLLB':   simulacao_nllb,
    'mBART':  simulacao_mbart,
}

resultados_modelo = {}
print('=== AVALIAÇÃO METEOR / chrF / TER — Bella Ciao ===')
for nome, trad_list in MODELOS_SIMS.items():
    scores = [calcular_metricas(t, r) for t, r in zip(trad_list, referencia_humana)]
    medias = {
        'METEOR': round(sum(s['METEOR'] for s in scores) / len(scores), 2),
        'chrF':   round(sum(s['chrF']   for s in scores) / len(scores), 2),
        'TER':    round(sum(s['TER']    for s in scores) / len(scores), 2),
    }
    resultados_modelo[nome] = medias
    print(f"  {nome}: METEOR={medias['METEOR']:.1f} | chrF={medias['chrF']:.1f} | TER={medias['TER']:.1f}")

print('\n  Nota: TER — quanto MENOR, melhor.')

# Gráfico comparativo METEOR / chrF / TER
modelos = list(resultados_modelo.keys())
cores = ['#2196F3', '#FF9800', '#4CAF50', '#9C27B0']
metricas_plot = [('METEOR', 'METEOR (maior=melhor)'), ('chrF', 'chrF (maior=melhor)'), ('TER', 'TER (menor=melhor)')]
x = np.arange(len(modelos))
largura = 0.25

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('METEOR · chrF · TER — Bella Ciao (IT→PT)', fontsize=14, fontweight='bold')

for ax, (met, titulo) in zip(axes, metricas_plot):
    vals = [resultados_modelo[m][met] for m in modelos]
    bars = ax.bar(modelos, vals, color=cores, edgecolor='white', alpha=0.85)
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{v:.1f}', ha='center', va='bottom', fontsize=9, fontweight='bold')
    ax.set_title(titulo, fontsize=11)
    ax.set_ylabel('Score')
    ax.grid(axis='y', linestyle='--', alpha=0.5)
    ax.set_ylim(0, max(vals) * 1.3 + 5)

plt.tight_layout()
plt.savefig('metricas_bella_ciao_meteor_chrf_ter.png', dpi=150, bbox_inches='tight')
plt.show()
print('Gráfico salvo em metricas_bella_ciao_meteor_chrf_ter.png')

"""---
## Análise Estatística — Desvio padrão · Diferença de médias · Teste pareado

> Esta seção adiciona, sobre os scores **por segmento** já calculados acima:
> - **Desvio padrão** (amostral, `ddof=1`), erro padrão e IC 95% por modelo;
> - **Teste de diferença de médias (omnibus):** ANOVA de um fator e, quando há ≥3 modelos, o teste de **Friedman** (pareado, não-paramétrico);
> - **Testes pareados par a par:** **t pareado** (`ttest_rel`) e **Wilcoxon** (signed-rank), com tamanho de efeito (Cohen *dz*) e correção de **Bonferroni**;
> - **Gráficos:** barras de média ± desvio padrão (com os pontos por segmento) e **mapa de calor** dos p-valores dos testes pareados.
>
> A avaliação é **pareada**: cada segmento (verso/parágrafo) é pontuado por todos os modelos, então as colunas ficam alinhadas pelo mesmo segmento.

"""

import warnings; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd
from scipy import stats
import itertools

# ---------------------------------------------------------------
# DESVIO PADRÃO + TESTE DE DIFERENÇA DE MÉDIAS + TESTE PAREADO
# (função reutilizável; avaliação pareada = mesmo segmento por modelo)
# ---------------------------------------------------------------
def analise_estatistica_modelos(scores_por_modelo, nome_metrica="Métrica",
                                maior_melhor=True, alpha=0.05, imprimir=True,
                                plotar=True, salvar_em=None):
    modelos = list(scores_por_modelo.keys())
    dados = {m: np.asarray(scores_por_modelo[m], dtype=float) for m in modelos}

    # ---- validação de tamanho (necessário para teste pareado) ----
    tamanhos = {m: len(v) for m, v in dados.items()}
    n = min(tamanhos.values())
    if len(set(tamanhos.values())) > 1:
        if imprimir:
            print(f"[aviso] modelos com nº de segmentos diferente {tamanhos}; "
                  f"truncando para n={n} para permitir teste pareado.")
        dados = {m: v[:n] for m, v in dados.items()}

    # =================================================================
    # 1) ESTATÍSTICAS DESCRITIVAS  (inclui o DESVIO PADRÃO pedido)
    # =================================================================
    linhas = []
    for m in modelos:
        x = dados[m]
        media = x.mean()
        desv = x.std(ddof=1)                       # desvio padrão amostral
        ep = desv / np.sqrt(len(x))                # erro padrão da média
        tcrit = stats.t.ppf(1 - alpha / 2, len(x) - 1)
        ic_low, ic_high = media - tcrit * ep, media + tcrit * ep
        linhas.append({
            "Modelo": m, "n": len(x),
            "Média": round(media, 3),
            "Desvio_Padrão": round(desv, 3),
            "Erro_Padrão": round(ep, 3),
            "IC95%_inf": round(ic_low, 3),
            "IC95%_sup": round(ic_high, 3),
        })
    desc = pd.DataFrame(linhas)
    melhor = (desc.loc[desc["Média"].idxmax()] if maior_melhor
              else desc.loc[desc["Média"].idxmin()])

    # =================================================================
    # 2) TESTE DE DIFERENÇA DE MÉDIAS (OMNIBUS)
    # =================================================================
    grupos = [dados[m] for m in modelos]
    omnibus = {}
    if len(modelos) >= 2:
        # ANOVA de um fator (paramétrica)
        f_stat, p_anova = stats.f_oneway(*grupos)
        omnibus["ANOVA_F"] = round(float(f_stat), 4)
        omnibus["ANOVA_p"] = float(p_anova)
        # Friedman (não-paramétrico, pareado) — exige >=3 grupos
        if len(modelos) >= 3:
            try:
                chi, p_fried = stats.friedmanchisquare(*grupos)
                omnibus["Friedman_chi2"] = round(float(chi), 4)
                omnibus["Friedman_p"] = float(p_fried)
            except Exception as e:
                omnibus["Friedman_erro"] = str(e)

    # =================================================================
    # 3) TESTES PAREADOS PAR A PAR
    # =================================================================
    pares = list(itertools.combinations(modelos, 2))
    n_comp = len(pares)
    linhas_par = []
    for a, b in pares:
        xa, xb = dados[a], dados[b]
        dif = xa - xb
        sd_dif = dif.std(ddof=1)
        if np.allclose(dif, 0):
            # diferença nula em todos os segmentos -> sem diferença
            t_stat, p_t, w_stat, p_w, dz = 0.0, 1.0, np.nan, 1.0, 0.0
        elif sd_dif == 0:
            # diferença CONSTANTE (variância zero) -> determinística
            t_stat, p_t = np.inf * np.sign(dif.mean()), 0.0
            try:
                w_stat, p_w = stats.wilcoxon(xa, xb)
            except Exception:
                w_stat, p_w = np.nan, 0.0
            dz = np.inf * np.sign(dif.mean())
        else:
            try:
                t_stat, p_t = stats.ttest_rel(xa, xb)
            except Exception:
                t_stat, p_t = np.nan, np.nan
            try:
                w_stat, p_w = stats.wilcoxon(xa, xb)
            except Exception:
                w_stat, p_w = np.nan, np.nan
            dz = dif.mean() / sd_dif
        p_bonf = min(p_t * n_comp, 1.0) if not np.isnan(p_t) else np.nan
        linhas_par.append({
            "Par": f"{a} vs {b}",
            "Dif_média": round(float(dif.mean()), 3),
            "t": (round(float(t_stat), 3) if np.isfinite(t_stat) else t_stat),
            "p_t_pareado": p_t,
            "p_Wilcoxon": p_w,
            "p_t_Bonferroni": p_bonf,
            "Cohen_dz": (round(float(dz), 3) if np.isfinite(dz) else dz),
            "Signif_(α=%.2f)" % alpha: "sim" if (not np.isnan(p_bonf) and p_bonf < alpha) else "não",
        })
    pareado = pd.DataFrame(linhas_par)

    # ---- impressão amigável ----
    if imprimir:
        print(f"\n{'='*70}\nANÁLISE ESTATÍSTICA — {nome_metrica} "
              f"({'maior=melhor' if maior_melhor else 'menor=melhor'}) | n={n} segmentos\n{'='*70}")
        print("\n• Descritivas (média ± desvio padrão):")
        print(desc.to_string(index=False))
        print(f"\n  → melhor média: {melhor['Modelo']} "
              f"({melhor['Média']} ± {melhor['Desvio_Padrão']})")
        if omnibus:
            print("\n• Teste de diferença de médias (omnibus):")
            if "ANOVA_p" in omnibus:
                sig = "DIFERENÇA significativa" if omnibus["ANOVA_p"] < alpha else "sem diferença significativa"
                print(f"    ANOVA 1 fator: F={omnibus['ANOVA_F']}, "
                      f"p={omnibus['ANOVA_p']:.4g}  → {sig}")
            if "Friedman_p" in omnibus:
                sig = "DIFERENÇA significativa" if omnibus["Friedman_p"] < alpha else "sem diferença significativa"
                print(f"    Friedman (pareado): χ²={omnibus['Friedman_chi2']}, "
                      f"p={omnibus['Friedman_p']:.4g}  → {sig}")
        print("\n• Testes PAREADOS par a par (t pareado + Wilcoxon):")
        pp = pareado.copy()
        for col in ["p_t_pareado", "p_Wilcoxon", "p_t_Bonferroni"]:
            pp[col] = pp[col].map(lambda v: f"{v:.4g}" if pd.notna(v) else "—")
        print(pp.to_string(index=False))
        print("\n  Nota: p_t_Bonferroni corrige o nº de comparações; "
              "Cohen_dz é o tamanho de efeito pareado.")

    # =================================================================
    # 4) GRÁFICOS  (desvio padrão + diferença de médias + teste pareado)
    # =================================================================
    if plotar:
        import matplotlib.pyplot as plt
        n_mod = len(modelos)
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13.5, 5.2),
                                       gridspec_kw={"width_ratios": [1.15, 1]})
        cores = plt.cm.Set2(np.linspace(0, 1, max(n_mod, 3)))[:n_mod]

        # --- AX1: barras média ± desvio padrão + pontos por segmento ---
        medias = np.array([dados[m].mean() for m in modelos])
        desvs = np.array([dados[m].std(ddof=1) for m in modelos])
        xpos = np.arange(n_mod)
        bars = ax1.bar(xpos, medias, yerr=desvs, capsize=6, color=cores,
                       edgecolor="white", alpha=0.85, error_kw={"elinewidth": 1.5})
        for i, m in enumerate(modelos):
            y = dados[m]
            jit = (np.random.RandomState(0).rand(len(y)) - 0.5) * 0.35
            ax1.scatter(np.full(len(y), i) + jit, y, s=16, color="#333",
                        alpha=0.45, zorder=3)
        # destaca o melhor
        idx_best = (int(medias.argmax()) if maior_melhor else int(medias.argmin()))
        bars[idx_best].set_edgecolor("#d62728")
        bars[idx_best].set_linewidth(2.5)
        for i, (mu, sd) in enumerate(zip(medias, desvs)):
            ax1.text(i, mu + sd + (medias.max() * 0.02 + 0.5),
                     f"{mu:.1f}±{sd:.1f}", ha="center", va="bottom",
                     fontsize=9, fontweight="bold")
        ax1.set_xticks(xpos)
        ax1.set_xticklabels(modelos, rotation=20, ha="right", fontsize=9)
        ax1.set_ylabel(nome_metrica)
        sentido = "maior=melhor" if maior_melhor else "menor=melhor"
        ax1.set_title(f"Média ± desvio padrão · pontos por segmento\n({sentido}; borda vermelha = melhor)",
                      fontsize=10)
        ax1.grid(axis="y", linestyle="--", alpha=0.4)

        # --- AX2: mapa de calor dos p-valores pareados (t pareado, Bonferroni) ---
        P = np.full((n_mod, n_mod), np.nan)
        idx = {m: i for i, m in enumerate(modelos)}
        for _, r in pareado.iterrows():
            a, b = r["Par"].split(" vs ")
            pv = r["p_t_Bonferroni"]
            P[idx[a], idx[b]] = pv
            P[idx[b], idx[a]] = pv
        with np.errstate(divide="ignore"):
            M = -np.log10(np.clip(P, 1e-300, 1.0))   # maior = mais significativo
        im = ax2.imshow(M, cmap="YlOrRd", vmin=0,
                        vmax=max(3.0, np.nanmax(M) if np.isfinite(np.nanmax(M)) else 3.0))
        ax2.set_xticks(range(n_mod)); ax2.set_yticks(range(n_mod))
        ax2.set_xticklabels(modelos, rotation=30, ha="right", fontsize=8)
        ax2.set_yticklabels(modelos, fontsize=8)

        def estrelas(p):
            if np.isnan(p): return ""
            if p < 0.001: return "***"
            if p < 0.01:  return "**"
            if p < 0.05:  return "*"
            return "ns"
        for i in range(n_mod):
            for j in range(n_mod):
                if i == j:
                    ax2.text(j, i, "—", ha="center", va="center", color="#999")
                elif not np.isnan(P[i, j]):
                    p = P[i, j]
                    txt = ("<0.001" if p < 0.001 else f"{p:.3f}") + f"\n{estrelas(p)}"
                    cor = "white" if M[i, j] > 2 else "black"
                    ax2.text(j, i, txt, ha="center", va="center", fontsize=7.5, color=cor)
        ax2.set_title("Teste pareado — p (t pareado, Bonferroni)\n*** p<0.001  ** p<0.01  * p<0.05  ns=não signif.",
                      fontsize=9.5)
        cb = fig.colorbar(im, ax=ax2, fraction=0.046, pad=0.04)
        cb.set_label("-log10(p)", fontsize=8)

        fig.suptitle(f"Análise estatística — {nome_metrica}", fontsize=13, fontweight="bold")
        fig.tight_layout(rect=[0, 0, 1, 0.95])
        if salvar_em:
            fig.savefig(salvar_em, dpi=150, bbox_inches="tight")
            if imprimir:
                print(f"  Gráfico salvo em {salvar_em}")
        plt.show()

    return {"descritivas": desc, "omnibus": omnibus, "pareado": pareado}

# >>> Requer 'MODELOS_SIMS', 'referencia_humana' e 'calcular_metricas' (célula acima).
_scores_seg = {met: {} for met in ['METEOR', 'chrF', 'TER']}
for _nome, _trad in MODELOS_SIMS.items():
    _por_verso = [calcular_metricas(t, r) for t, r in zip(_trad, referencia_humana)]
    for met in ['METEOR', 'chrF', 'TER']:
        _scores_seg[met][_nome] = np.array([s[met] for s in _por_verso])
for _metrica, _maior in [('METEOR', True), ('chrF', True), ('TER', False)]:
    analise_estatistica_modelos(_scores_seg[_metrica], _metrica, maior_melhor=_maior)