# -*- coding: utf-8 -*-
"""poema_l_infinito_t5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzrQS-erYxPUPEwsjtBOPu3U8KiLgVYv

# Tabela 11 — Divergência Métrica na Avaliação da Saída do T5
## Poema *L'Infinito* (Giacomo Leopardi, 1819) — IT → PT

**Objetivo:** Reproduzir computacionalmente o fenômeno documentado — a **mesma saída** de tradução automática recebe três avaliações radicalmente divergentes:

| Instrumento | Score do T5 | Interpretação |
|---|---|---|
| BLEU direto (vs. referência humana) | 0,00 | Ausência total de correspondência tradutória |
| IFC (Índice de Fidelidade Cultural) | 0,00 | Nenhum termo culturalmente marcado preservado |
| RTT (BLEU de ida e volta) | 100,00 | **Artefato:** recuperação trivial do texto-fonte não traduzido |

> O escore de 100,00 no RTT **não** mede qualidade tradutória — é um artefato gerado porque o modelo devolveu o original em italiano sem traduzir.
"""

!pip install sacrebleu -q
import sacrebleu

"""## 1. Textos"""

# Texto-fonte em italiano — domínio público (Leopardi morreu em 1837).
FONTE_IT = [
    "Sempre caro mi fu quest'ermo colle,",
    "e questa siepe, che da tanta parte",
    "dell'ultimo orizzonte il guardo esclude.",
    "Ma sedendo e mirando, interminati",
    "spazi di la da quella, e sovrumani",
    "silenzi, e profondissima quiete",
    "io nel pensier mi fingo, ove per poco",
    "il cor non si spaura. E come il vento",
    "odo stormir tra queste piante, io quello",
    "infinito silenzio a questa voce",
    "vo comparando: e mi sovvien l'eterno,",
    "e le morte stagioni, e la presente",
    "e viva, e il suon di lei. Cosi tra questa",
    "immensita s'annega il pensier mio:",
    "e il naufragar m'e dolce in questo mare.",
]

# Referência humana em português (gold standard do BLEU direto).
REFERENCIA_PT = [
    "Sempre caro me foi este ermo outeiro,",
    "e esta sebe, que de tao grande parte",
    "do ultimo horizonte o olhar exclui.",
    "Mas sentado e contemplando, intermineveis",
    "espacos para alem dela, e sobre-humanos",
    "silencios, e profundissima quietude",
    "eu no pensamento finjo, onde por pouco",
    "o coracao nao se apavora. E como o vento",
    "ouco sussurrar entre estas plantas, eu aquele",
    "infinito silencio a esta voz",
    "vou comparando: e me ocorre o eterno,",
    "e as mortas estacoes, e a presente",
    "e viva, e o som dela. Assim entre esta",
    "imensidao se afoga o pensamento meu:",
    "e o naufragar me e doce neste mar.",
]

# Saída do T5 (IT → PT): modelo devolveu o texto-fonte inalterado (função identidade).
SAIDA_T5 = list(FONTE_IT)

print(f"Versos no fonte:     {len(FONTE_IT)}")
print(f"Versos na referência: {len(REFERENCIA_PT)}")
print(f"Versos na saída T5:  {len(SAIDA_T5)}")
print("\nPrimeiro verso — fonte IT   :", FONTE_IT[0])
print("Primeiro verso — referência PT:", REFERENCIA_PT[0])
print("Primeiro verso — saída T5     :", SAIDA_T5[0])

"""## 2. Definição das Métricas"""

def bleu(hipotese, referencia):
    """BLEU de corpus (0–100) entre duas listas de versos alinhados."""
    return sacrebleu.corpus_bleu(hipotese, [referencia]).score


# Termos culturalmente/poeticamente marcados e suas formas esperadas em PT.
TERMOS_MARCADOS = {
    "ermo colle":           ["ermo outeiro", "colina solitaria", "monte ermo"],
    "siepe":                ["sebe"],
    "sovrumani silenzi":    ["silencios sobre-humanos", "sobre-humanos"],
    "profondissima quiete": ["profundissima quietude"],
    "il cor":               ["o coracao"],
    "naufragar":            ["naufragar"],   # cognato: só conta se em frase PT
}


def ifc(saida_versos, mapa_termos):
    """
    Índice de Fidelidade Cultural (0–100).
    Conta a fração de termos marcados cuja forma-alvo em PORTUGUÊS
    aparece na saída. Se a saída está em italiano (não traduzida),
    nenhuma forma-alvo ocorre → IFC = 0.
    """
    texto = " ".join(saida_versos).lower()
    em_portugues = any(marca in texto for marca in
                       ["coracao", "silencios", "quietude", "sebe", "outeiro"])
    if not em_portugues:
        return 0.0
    preservados = sum(
        1 for formas_alvo in mapa_termos.values()
        if any(f.lower() in texto for f in formas_alvo)
    )
    return 100.0 * preservados / len(mapa_termos)


def rtt_bleu(saida_forward, fonte):
    """
    RTT (Round-Trip Translation) — BLEU de ida e volta.
      ida  : IT --T5--> saida_forward
      volta: saida_forward --T5--> reconstrução
    Como a ida foi a identidade, a volta também o é.
    Logo: reconstrução == fonte e BLEU satura em 100 — artefato.
    """
    reconstrucao = list(saida_forward)   # volta = identidade também
    return bleu(reconstrucao, fonte)


print("Funções definidas: bleu(), ifc(), rtt_bleu()")

"""## 3. Cálculo dos Scores"""

bleu_direto = bleu(SAIDA_T5, REFERENCIA_PT)
indice_ifc  = ifc(SAIDA_T5, TERMOS_MARCADOS)
escore_rtt  = rtt_bleu(SAIDA_T5, FONTE_IT)

print(f"BLEU direto (vs. ref. humana) : {bleu_direto:6.2f}")
print(f"IFC (Fidelidade Cultural)     : {indice_ifc:6.2f}")
print(f"RTT (BLEU de ida e volta)     : {escore_rtt:6.2f}")

"""## 4. Tabela de Resultados (Tabela 11)"""

sep  = "=" * 92
linha = "-" * 92

print()
print("TABELA 11 — Divergência métrica na avaliação da saída do T5")
print("            para o poema L'Infinito (IT → PT)")
print(sep)
print(f"{'Instrumento':<30}{'Score do T5':>12}   {'Interpretação'}")
print(linha)
print(f"{'BLEU direto (vs. ref. humana)':<30}{bleu_direto:>11.2f}   "
      "Ausência total de correspondência tradutória")
print(f"{'IFC':<30}{indice_ifc:>11.2f}   "
      "Nenhum termo culturalmente marcado preservado")
print(f"{'RTT (BLEU de ida e volta)':<30}{escore_rtt:>11.2f}   "
      "Artefato: recuperação trivial do texto-fonte")
print(sep)
print("Fonte: elaborado pelo autor (2026).")
print("O score de 100,00 na análise RTT não reflete qualidade tradutória,")
print("mas a recuperação trivial do texto-fonte que não foi traduzido.")
print()

"""## 5. Contraprova — Por que o RTT é Enganoso

Se o modelo **tivesse** traduzido de fato, a volta **não** devolveria o italiano original e o RTT cairia bem abaixo de 100.
Usamos a referência humana como proxy de uma boa tradução (ida).
"""

rtt_se_traduzisse = bleu(REFERENCIA_PT, FONTE_IT)   # PT bem traduzido vs IT original

print("Contraprova (mesma métrica RTT, mas com tradução REAL na ida):")
print(f"  RTT quando há tradução genuína ......... {rtt_se_traduzisse:6.2f}  "
      "(quebra o artefato de 100,00)")
print(f"  RTT quando o modelo NÃO traduz ......... {escore_rtt:6.2f}  "
      "(satura justamente por não traduzir)")
print()
print("Conclusão: RTT = 100 é sintoma de FALHA, não de acerto.")

"""## 7. Métricas de Superfície — chrF, chrF++ e TER

A Tabela 11 completa (conforme apresentada no slide 13 do TCC) inclui também
três métricas de sobreposição de superfície que revelam **por que o BLEU isolado
é insuficiente** no par IT→PT:

| Métrica | Interpretação | Valor esperado (T5) |
|---|---|---|
| **chrF** | F-score de n-gramas de *caracteres* | Inflado por cognatos IT-PT |
| **chrF++** | chrF + n-gramas de palavras (β=2) | Idem, efeito de falso positivo |
| **TER** | Taxa de edições p/ igualar a referência | Alto = má tradução |

> **Atenção:** chrF e chrF++ elevados **não** indicam boa tradução aqui —
> italiano e português compartilham grafias de raiz latina, inflando o F-score
> mesmo quando nada foi traduzido.

"""

# Métricas de superfície: chrF, chrF++ e TER
# Requer sacrebleu >= 2.0 (já instalado na Célula 1)

# ── chrF (n-gramas de caracteres, ordem 6, β=2) ──────────────────────────
chrf_score = sacrebleu.corpus_chrf(
    SAIDA_T5,
    [REFERENCIA_PT],
    char_order=6,
    word_order=0,      # chrF puro (sem n-gramas de palavras)
    beta=2
).score

# ── chrF++ (chrF + n-gramas de palavras, word_order=2) ───────────────────
chrfpp_score = sacrebleu.corpus_chrf(
    SAIDA_T5,
    [REFERENCIA_PT],
    char_order=6,
    word_order=2,      # chrF++ inclui bigramas de palavras
    beta=2
).score

# ── TER (Translation Edit Rate) — quanto menor, melhor ───────────────────
ter_score = sacrebleu.corpus_ter(
    SAIDA_T5,
    [REFERENCIA_PT]
).score

print(f"chrF   = {chrf_score:.2f}  ← inflado por cognatos IT-PT (falso positivo)")
print(f"chrF++ = {chrfpp_score:.2f}  ← idem, reforça o efeito de proximidade linguística")
print(f"TER    = {ter_score:.2f}  ← quase 100% de edições necessárias (má tradução)")

"""### Interpretação dos valores

- **chrF = 36,79** — aparentemente razoável, mas decorre da coincidência de caracteres
  entre línguas irmãs, não de tradução efetiva.
- **chrF++ = 32,79** — resultado similar ao chrF; a inclusão de bigramas de palavras
  não elimina o "falso positivo" por proximidade linguística.
- **TER = 82,18** — quase 82% dos tokens precisariam ser editados para que a saída
  do T5 se iguale à referência humana. Confirma que nada foi traduzido.

Combinados com **BLEU = 6,24**, **IFC = 0,00** e **RTT = 100,00**, esses valores
compõem a **Tabela 11 completa** do TCC e demonstram que métricas de superfície
sozinhas são insuficientes para detectar a falha de não-tradução no par IT→PT.

"""

# Tabela 11 completa — todos os instrumentos reunidos

sep   = "=" * 92
linha = "-" * 92

print()
print("TABELA 11 — Divergência métrica na avaliação da saída do T5")
print("            para o poema L'Infinito (IT → PT)  [versão completa]")
print(sep)
print(f"{'Instrumento':<38} {'Score T5':>9}   {'Interpretação'}")
print(linha)

# Métricas de sobreposição de superfície (n-gramas / caracteres)
print(f"{'Métricas de sobreposição de superfície (n-gramas / caracteres)'}")
print(f"  {'BLEU direto (vs. ref. humana)':<36} {bleu_direto:>9.2f}   Praticamente nulo; resíduo de cognatos")
print(f"  {'chrF':<36} {chrf_score:>9.2f}   Inflado por coincidência de caracteres IT-PT")
print(f"  {'chrF++':<36} {chrfpp_score:>9.2f}   Mesmo efeito do chrF, inclui n-gramas de palavras")
print(f"  {'TER':<36} {ter_score:>9.2f}   ~82% de edições necessárias (menor=melhor)")
print(linha)

# Fidelidade léxico-cultural
print(f"{'Fidelidade léxico-cultural'}")
print(f"  {'IFC (Índice de Fidelidade Cultural)':<36} {indice_ifc:>9.2f}   Nenhum termo culturalmente marcado preservado")
print(linha)

# Métrica de ida e volta
print(f"{'Métrica de ida e volta'}")
print(f"  {'RTT (BLEU de ida e volta)':<36} {escore_rtt:>9.2f}   Artefato: recuperação trivial do texto-fonte")
print(sep)
print()
print("Fonte: elaborado pelo autor (2026).")
print("TER: quanto MENOR, melhor. Todos os demais: quanto MAIOR, melhor.")
print("chrF e chrF++ elevados = FALSO POSITIVO por proximidade linguística IT-PT.")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle("Tabela 11 — Avaliação Multimétrica da Saída do T5 para L'Infinito (IT→PT)",
             fontsize=12, fontweight='bold', y=1.02)

# ── Painel esquerdo: chrF / chrF++ / TER vs BLEU ─────────────────────────
ax1 = axes[0]
metricas_sup = ["BLEU\ndireto", "chrF", "chrF++", "TER*"]
valores_sup  = [bleu_direto, chrf_score, chrfpp_score, ter_score]
cores_sup    = ["#e34948", "#eda100", "#eda100", "#e34948"]

bars1 = ax1.bar(metricas_sup, valores_sup, color=cores_sup, width=0.5,
                edgecolor="white", linewidth=0.8, zorder=3)
for bar, v in zip(bars1, valores_sup):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1.5,
             f"{v:.2f}", ha="center", va="bottom", fontsize=11, fontweight="bold")

ax1.set_ylim(0, 115)
ax1.set_ylabel("Score (0–100)", fontsize=10)
ax1.set_title("Métricas de superfície\n(* TER: menor = melhor)", fontsize=10)
ax1.axhline(100, color="#aaa", linewidth=0.7, linestyle="--")
ax1.text(3.45, 101.5, "máx", fontsize=8, color="#aaa")
ax1.set_facecolor("#fafafa")
ax1.grid(axis="y", color="#e8e8e8", zorder=0)
ax1.spines[["top","right"]].set_visible(False)
falso  = mpatches.Patch(color="#eda100", label="Falso positivo (cognatos IT-PT)")
falha  = mpatches.Patch(color="#e34948", label="Falha de tradução")
ax1.legend(handles=[falha, falso], fontsize=8, loc="upper left")

# ── Painel direito: IFC e RTT ─────────────────────────────────────────────
ax2 = axes[1]
metricas_cult = ["IFC\n(Fidelidade Cultural)", "RTT\n(BLEU ida e volta)"]
valores_cult  = [indice_ifc, escore_rtt]
cores_cult    = ["#e34948", "#eda100"]

bars2 = ax2.bar(metricas_cult, valores_cult, color=cores_cult, width=0.4,
                edgecolor="white", linewidth=0.8, zorder=3)
for bar, v in zip(bars2, valores_cult):
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1.5,
             f"{v:.2f}", ha="center", va="bottom", fontsize=12, fontweight="bold")

ax2.set_ylim(0, 115)
ax2.set_ylabel("Score (0–100)", fontsize=10)
ax2.set_title("Instrumentos originais do TCC\n(IFC e RTT)", fontsize=10)
ax2.axhline(100, color="#aaa", linewidth=0.7, linestyle="--")
ax2.text(1.32, 101.5, "máx", fontsize=8, color="#aaa")
ax2.set_facecolor("#fafafa")
ax2.grid(axis="y", color="#e8e8e8", zorder=0)
ax2.spines[["top","right"]].set_visible(False)
artefato = mpatches.Patch(color="#eda100", label="Artefato (RTT satura sem traduzir)")
ax2.legend(handles=[falha, artefato], fontsize=8, loc="upper left")

plt.tight_layout()
plt.savefig("tabela11_completa_multimetrica.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figura salva: tabela11_completa_multimetrica.png")

"""## 6. Visualização Comparativa"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

instrumentos = ["BLEU direto\n(vs. ref. humana)", "IFC\n(Fidelidade Cultural)", "RTT\n(BLEU ida e volta)"]
scores       = [bleu_direto, indice_ifc, escore_rtt]
cores        = ["#e34948", "#e34948", "#eda100"]

fig, ax = plt.subplots(figsize=(8, 4.5))
bars = ax.bar(instrumentos, scores, color=cores, width=0.45, zorder=3, edgecolor="white", linewidth=0.8)

for bar, score in zip(bars, scores):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1.5,
            f"{score:.2f}", ha="center", va="bottom", fontsize=13, fontweight="bold")

ax.set_ylim(0, 115)
ax.set_ylabel("Score (0–100)", fontsize=11)
ax.set_title("Tabela 11 — Divergência Métrica: Saída do T5 para L'Infinito (IT→PT)",
             fontsize=11, pad=12)
ax.axhline(100, color="#888", linewidth=0.8, linestyle="--", zorder=2)
ax.text(2.38, 101.5, "máximo possível", fontsize=9, color="#888")
ax.set_facecolor("#fafafa")
ax.grid(axis="y", color="#e0e0e0", zorder=0)
ax.spines[["top","right"]].set_visible(False)

artefato = mpatches.Patch(color="#eda100", label="Artefato (RTT satura por não traduzir)")
falha    = mpatches.Patch(color="#e34948", label="Falha de tradução (BLEU/IFC = 0)")
ax.legend(handles=[falha, artefato], fontsize=9, loc="upper left")

plt.tight_layout()
plt.savefig("tabela11_divergencia_metrica.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figura salva: tabela11_divergencia_metrica.png")